# TCL File Generated by Component Editor 10.1sp1
# Wed Jun 25 14:05:01 EDT 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | audio "Audio" v1.0.1
# | null 2014.06.25.14:05:01
# | 
# | 
# | N:/MTE325/MTE325/Lab2/files/audio/hdl/Audio.v
# | 
# |    ./hdl/Audio.v syn, sim
# |    ./hdl/AUDIO_DAC_FIFO.v syn, sim
# |    ./hdl/FIFO_16_256.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module audio
# | 
set_module_property NAME audio
set_module_property VERSION 1.0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "UW ECE"
set_module_property DISPLAY_NAME Audio
set_module_property TOP_LEVEL_HDL_FILE hdl/Audio.v
set_module_property TOP_LEVEL_HDL_MODULE Audio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/Audio.v {SYNTHESIS SIMULATION}
add_file hdl/AUDIO_DAC_FIFO.v {SYNTHESIS SIMULATION}
add_file hdl/FIFO_16_256.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_clock
# | 
add_interface avalon_slave_0_clock clock end
set_interface_property avalon_slave_0_clock clockRate 0

set_interface_property avalon_slave_0_clock ENABLED true

add_interface_port avalon_slave_0_clock iWR_CLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_clock_reset
# | 
add_interface avalon_slave_0_clock_reset reset end
set_interface_property avalon_slave_0_clock_reset associatedClock avalon_slave_0_clock
set_interface_property avalon_slave_0_clock_reset synchronousEdges DEASSERT

set_interface_property avalon_slave_0_clock_reset ENABLED true

add_interface_port avalon_slave_0_clock_reset iRST_N reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_export
# | 
add_interface avalon_slave_0_export conduit end

set_interface_property avalon_slave_0_export ENABLED true

add_interface_port avalon_slave_0_export oAUD_BCK export Output 1
add_interface_port avalon_slave_0_export oAUD_DATA export Output 1
add_interface_port avalon_slave_0_export oAUD_LRCK export Output 1
add_interface_port avalon_slave_0_export oWR_FULL export Output 1
add_interface_port avalon_slave_0_export iCLK_18_4 export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment NATIVE
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock avalon_slave_0_clock
set_interface_property avalon_slave_0 associatedReset avalon_slave_0_clock_reset
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 1
set_interface_property avalon_slave_0 holdTime 2
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 20
set_interface_property avalon_slave_0 timingUnits Nanoseconds
set_interface_property avalon_slave_0 writeWaitStates 20
set_interface_property avalon_slave_0 writeWaitTime 20

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 iDATA writedata Input 16
add_interface_port avalon_slave_0 iWR write Input 1
# | 
# +-----------------------------------
