# TCL File Generated by Component Editor 10.1sp1
# Wed Jun 25 14:05:23 EDT 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | open_i2c "Open_I2C" v1.0.1
# | null 2014.06.25.14:05:23
# | 
# | 
# | N:/MTE325/MTE325/Lab2/files/open_i2c/hdl/i2c_master_top.vhd
# | 
# |    ./hdl/i2c_master_bit_ctrl.vhd syn, sim
# |    ./hdl/i2c_master_byte_ctrl.vhd syn, sim
# |    ./hdl/i2c_master_top.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module open_i2c
# | 
set_module_property NAME open_i2c
set_module_property VERSION 1.0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "UW ECE"
set_module_property DISPLAY_NAME Open_I2C
set_module_property TOP_LEVEL_HDL_FILE hdl/i2c_master_top.vhd
set_module_property TOP_LEVEL_HDL_MODULE i2c_master_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/i2c_master_bit_ctrl.vhd {SYNTHESIS SIMULATION}
add_file hdl/i2c_master_byte_ctrl.vhd {SYNTHESIS SIMULATION}
add_file hdl/i2c_master_top.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_clock
# | 
add_interface avalon_slave_0_clock clock end
set_interface_property avalon_slave_0_clock clockRate 0

set_interface_property avalon_slave_0_clock ENABLED true

add_interface_port avalon_slave_0_clock wb_clk_i clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_clock_reset
# | 
add_interface avalon_slave_0_clock_reset reset end
set_interface_property avalon_slave_0_clock_reset associatedClock avalon_slave_0_clock
set_interface_property avalon_slave_0_clock_reset synchronousEdges DEASSERT

set_interface_property avalon_slave_0_clock_reset ENABLED true

add_interface_port avalon_slave_0_clock_reset arst_i reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_export
# | 
add_interface avalon_slave_0_export conduit end

set_interface_property avalon_slave_0_export ENABLED true

add_interface_port avalon_slave_0_export wb_rst_i export Input 1
add_interface_port avalon_slave_0_export scl_pad_i export Input 1
add_interface_port avalon_slave_0_export scl_pad_o export Output 1
add_interface_port avalon_slave_0_export scl_padoen_o export Output 1
add_interface_port avalon_slave_0_export sda_pad_i export Input 1
add_interface_port avalon_slave_0_export sda_pad_o export Output 1
add_interface_port avalon_slave_0_export sda_padoen_o export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment NATIVE
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock avalon_slave_0_clock
set_interface_property avalon_slave_0 associatedReset avalon_slave_0_clock_reset
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 8
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 wb_adr_i address Input 3
add_interface_port avalon_slave_0 wb_dat_i writedata Input 8
add_interface_port avalon_slave_0 wb_dat_o readdata Output 8
add_interface_port avalon_slave_0 wb_we_i write Input 1
add_interface_port avalon_slave_0 wb_stb_i chipselect Input 1
add_interface_port avalon_slave_0 wb_cyc_i byteenable Input 1
add_interface_port avalon_slave_0 wb_ack_o waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_irq
# | 
add_interface avalon_slave_0_irq interrupt end
set_interface_property avalon_slave_0_irq associatedAddressablePoint avalon_slave_0
set_interface_property avalon_slave_0_irq associatedClock avalon_slave_0_clock
set_interface_property avalon_slave_0_irq associatedReset avalon_slave_0_clock_reset

set_interface_property avalon_slave_0_irq ENABLED true

add_interface_port avalon_slave_0_irq wb_inta_o irq Output 1
# | 
# +-----------------------------------
